### ISSUE TITLE
Ultra-strict checklist

### ISSUE THREAD

**Issue by petrhejna** [petrhejna/petrhejna#83]
- [x] Mocking is forbidden.
- [x] Everything is final or abstract.
- [ ] Functional and stateless (the state is completely separated from logic).
